roast_quotes = [
    "I am not saying that i hate you. I am just saying if you got hit by a bus, i would be driving that bus.",
    "I would slap you but that would be an animal abuse.",
    "Did you hear that? That's the sound of no one caring....lol.",
    "You're the reason your dad drinks.",
    "At least there's one good thing about your body. It isn't as ugly as your face.",
    "You're like a light switch, even a little kid can turn you on.",
    "The only positive thing about you is your HIV status.",
    "Your face could scare the shit out of a toilet.",
    "You must have been born on a highway because thats where most accidents happen.",
    "Being a dick to everyone won't make yours any bigger.",
    "Roses are red, shit is brown, shut the fuck up, and sit the fuck down.",
    "I'm jealous of people that don't know you!",
    "There is someone out there for everyone. For you, it’s a therapist.",
    "I would smack you, but I’m against animal abuse.",
    "If I wanted to kill myself, I would simply jump from your ego to your IQ.",
    "I can’t wait to spend my whole life without you.",
    "Whoever told you to be yourself, gave you a bad advice.",
    "I didn’t mean to offend you… but it was a huge plus.",
    "I don’t hate you, but if you were drowning, I would give you a high five.",
    "If I throw a stick, will you leave me too?",
    "Sorry I can’t think of an insult dumb enough for you to understand.",
    "I don’t know what makes you so stupid, but it works.",
    "Whatever doesn’t kill you, disappoints me.",
    "It is hilarious how you are trying to fit your entire vocabulary into one sentence.",
    "I like the way you comb your hair, so horns don’t show up.",
    "Have a nice day… somewhere else.",
    "I would call you an idiot, but it would be an insult for stupid people.",
    "I told my therapist about you; she didn’t believe me.",
    "Did you know your incubator had tinted windows? That explains a lot.",
    "The last time I saw something like you, it was behind metal grids.",
    "If I had a dollar every time you shut up, I would give it back as a thank you.",
    "You were so happy for the negativity of your Covid test, we didn’t want to spoil the happiness by telling you it was IQ test.",
    "Honey, only thing bothering me is placed between your ears.",
    "Only thing that is pleasing about our relationship is that you are no longer in it.",
    "Every time I have a stick in my hand, you look like a pinata.",
    "You are like a software update. every time I see you, I immediately think “not now”.",
    "When I look at you, I think to myself where have you been my whole life? Can you go back there?",
    "You can’t imagine how much happiness you can bring… by leaving the room.",
    "I know you don’t like me, that says a lot. You need to acquire a better taste.",
    "It’s all about balance… you start talking, I stop listening.",
    "Are you talking to me? I thought you only talk behind my back.",
    "Everyone is allowed to act stupid once, but you… you are abusing that privilege.",
    "Cry me a river, then drown yourself in it.",
    "Ola soy Dora. Can you help me find where we asked?",
    "Somewhere tree is producing oxygen for you. I’m sorry for it.",
    "Earth is full. Go home.",
    "Everyone has purpose in this life, yours is to become an organ donor.",
    "Why are you rolling your eyes? Are you looking for your brain?",
    "You didn’t change since last time I saw you. You should.",
    "What is wrong with you? Have you had too many drugs in mental hospital today?",
    "It is better to shut your mouth and make people think you are stupid than open it and remove all doubt.",
    "Hurting you is the least thing I want to do… but it’s still in the list.",
    "Oh, sorry, did the middle of my sentence interrupted the beginning of yours?",
    "Why are you gae?",
    "Which sexual position produces the ugliest children? Ask your mother.",
    "Begone thot!", "ligma balls", "joe momma is fat and geh",
    " I’m not saying you’re ugly, but if I throw a stick, you fetch the bastard and bring it back.",
    "Before we start, dude, you’ve got something on your chin … no, not that one … nope, keep going.",
    "If your brain was made of dynamite, you couldn’t even blow your nose!",
    "I’m not saying you’re boring, but if you’re a fucking gray sprinkle on a rainbow cupcake!",
    "You and I go way back, and you’ve always been annoying. I mean, you even used to make your happy meal cry.",
    "We’ve been happily married for three months; shame it’s taken ten years to hit that number.",
    "I know our son got his brains from you because, well, I still have mine.",
    "The only reason I take you everywhere with me is that I’d rather do that than kiss your ugly face goodbye.",
    "You love to act stupid. I know because I live with you, you’re naturally way dumber than that.",
    "You’re so ugly your face makes onions cry!",
    "Roasting you isn’t easy. It’s hard enough to imagine you with a personality.",
    "I’m not saying you’re ugly, but you’re the reason God created miscarriages!",
    "Give me a minute; I’m trying to think of an insult that’s dumb enough for you to understand!",
    "I’m not saying you’re ugly, but the reason nobody wants to sleep with you is that they don’t want to be prosecuted for animal abuse.",
    "You’ve got so many gaps in your teeth it looks like your tongue is in jail.",
    "Maybe you should try to eat make-up to improve your ugly personality.",
    "I know it looks like I’m listening to you, but really I’m just visualizing duck tape over your mouth.",
    "This will be the first and last roast of the night, as we’ve already used up your entire vocabulary.",
    "Do you know the best part about being your friend? Not having to see you all the time.",
    "You’re the reason the gene pool should really have lifeguards.",
    "The only way you’d get hurt from doing exercise would be if you sprained your finger, changing the channel.",
    "Some might call you a smart ass, others a dumb ass; I say you’re just an ass.",
    "It’s a parents job to raise their children right. So looking at you, it’s no wonder your dad quit after just one day.",
    "Your bad personality is the reason I prefer animals to humans.",
    "There’s somebody out there for everybody. For you, it’s a psychiatrist.",
    "You’re so annoying; it’s because of you God gave us all a middle finger.",
    "You’re like the first slice of bread in a loaf. You get touched by everybody but wanted by none.",
    "I’m sorry that this roast uses your entire vocabulary.",
    "I would explain all of these roasts to you, but I forgot to bring you an English to dumbass dictionary.",
    "The only reason someone would go down on you is in the hope that your clitoris was an off button.",
    "You’re more disappointing than an unsalted pretzel.",
    "I’m not saying you’re a commitment-phobe, but baby, my phone battery lasts longer than your relationships.",
    "I don’t want to be mean, but babe, my hair straightener is hotter than you are.",
    "I was going to stand here and make a joke about your life, but hey, it looks like life got there first.",
    "It must be fun to wake up each morning knowing that you are that much closer to achieving your dreams of complete and utter mediocrity.",
    "You’re such a momma’s boy, but newsflash, that makes you a son, not a sun, so stop thinking the earth revolves around you.",
    "Accidents happen; the proof is sitting right here.",
    "You’re so irritating you should come with a warning label",
    "Everyone is entitled to one, but yours is always the incorrect opinion.",
    "Whenever you open your mouth, it’s like, ‘Woah, somebody took too many drugs this morning.’",
    "Every day I hope you get your chapstick confused with a glue stick so I can get a bit of peace and quiet.",
    "You’re like the human version of athlete’s foot – annoying and hard to get rid of.",
    "If you ever feel suicidal, at least you can jump off your own ego.",
    "If your mum got given one piece of bad advice, it was not to swallow.",
    "I believe you can achieve anything. Look around you; there are remarkably dumb people everywhere who you could aspire to be.",
    "I’m not saying you’re ugly, but my baby’s diaper rash is nicer to look at.",
    "We’ve been best friends a long time, but you’re the reason they put external use only on shampoo bottles.",
    "And the best part of our relationship is the fact that you are no longer in it.",
    "It’s not that you’re annoying; it’s just that I’d liken you to the human version of period cramps.",
    "Your only chance of getting laid is if you were to crawl inside a chicken’s butt and wait.",
    "You’re not that ugly, I guess. I mean, my middle finger gets a boner every time it sees you!",
    "I bet I could remove 90% of your good looks with a moist towelette.",
    "I’m so sorry if my brutal honesty inconvenienced your overinflated sense of self.",
    "It’s not that I don’t listen to you when you talk. It’s just that there is only so much stupid information I can process in one go.",
    "I’m not an astronomer, but I am pretty sure the world revolves around the sun and not you.",
    "You might look attractive, but I’d have to put a paper bag over that personality.",
    "Everybody brings happiness to a room. You just do it when you leave!",
    "You remind me of a cloud; when you disappear, my day gets that much brighter.",
    "Your birth certificate should be a letter of apology from Durex.",
    "Light travels faster than sound. This must be why you appear bright until you open your mouth.",
    "It must be tough to accept that even Donald Trump is more intelligent than you are.",
    "Looking at you reminded me to take my contraception. I can’t risk giving birth to someone that ugly.",
    "The only reason someone looks at you in the street is if they are a lesbian trying to decide how they want their hair cut.",
    "We were going to roast you, but apparently, it’s not good for the environment to burn trash.",
    "You are even more useless than the ‘ueue’ in queue.",
    "I would call you an idiot, but that would be a horrible insult to stupid people everywhere.",
    "Have you ever tried putting makeup on your toast to try and make your personality prettier?",
    "Walls may have ears, but count yourself lucky they don’t have mouths because all they would do is laugh at you.",
    "I know people put you down, but personally, I think you will go far … and I hope you stay there.",
    "When I look at you, I can’t help but wonder, how the hell were you the fastest sperm?",
    "If laughter is the best medicine, your face might very well be a cure for cancer!",
    "I think I found your purpose in life… to be an organ donor.",
    "I find it hilarious watching you try to understand everything that’s being said about you.",
    "I’m not saying you’re dumb but a glowstick has a brighter future than you do.",
    "I might be fully vaccinated but I’m still not going to hang out with you.",
    "Use the following comebacks when you feel the time is right, to ensure you leave the roast with more than just emotional scars and crippling self-doubt.",
    "I’d give you a nasty look but you’ve already got one.",
    "Were you born this stupid or did you take lessons?",
    "The real heroes in this world are the ones who live with you.",
    "If I wanted to hear from an asshole, I’d fart.",
    "You are so full of shit, the toilet’s jealous.",
    "I’ve been called worse by better.",
    "Do your parents even realize they’re living proof that two wrongs don’t make a right?",
    "Most mistakes can be fixed, you are the exception that proves the rule.",
    "I’ve heard a smarter statement come out in a fart.",
    "You’re not simply a drama queen. You’re the whole royal family!",
    "You tried hard there, so I’m going to give you a participation award.",
    "Being a dick to me won’t make yours bigger.",
    "Large and in charge is not a synonym for being a fat asshole.", 
    "The truth will set you free. You suck. Ok, you’re free to go."
]

response = [
    "It's a certain.", "I'm not sure but ur def stupid.", "lol literally no",
    "yes, idiot", "Are you a retard?", "How am i supposed to know?...dick",
    "no bruh", "yes smh", "don't know, don't care", "ur delusional", "ur mom",
    "yepp!", "lol...that's so true", "i don't wanna hurt your feelings but no",
    "That's a harsh reality", "never dumbass!", "ok whatever, yes",
    "heck no! You know that better than anybody", "lol really?","ask me later when im less busy with your mom"
]

depart = [
    "Get lost lol.", "Die.", "You think I care?", "I'm gonna miss you honey.",
    "Aunt May: Peter, don't leave me.",
    "I feel so horny, please don't leave uwu."
]

bot_roast = [
    "bot sucks", "bot is shit", "bot is annoying", "tatti bot", "bot tatti ",
    "chutiya bot", "bot chutiya he", "bot is so annoying"
]

user_greet = ["hi", "hello", "hey"]

comebacks = [
    "lmfao", "that's what she said", "your life is a joke",
    "that would be you", "shit", "serves you right...lol", "joe momma",
    "ligma balls"
]

greet = [
    "sup!",
    "hello",
    "hi",
    "hey",
]

imagine_words = [
    "Imagined.", "ngl I feel so dumb right now.", "Go home.", "XD",
    "I can't even imagine bro...", "shit never gets old", "That's cringe",
    "gross"
]

status = ["dead", "ur mom"]
